TRUNCATE TABLE leads;

INSERT INTO leads (
  name, company, role,
  industry, tags,
  description, product,
  value_proposition, target_market,
  recent_activity, strategic_focus, additional_context
)
VALUES
(
  'Emma Rodriguez',
  'Salesloft',
  'VP of Sales Engineering',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Company specializing in sales engagement automation for revenue teams',
  'AI-powered sales engagement platform with multi-channel sequencing',
  'Increase sales rep productivity and improve connect rates',
  'Mid-market B2B companies with outbound sales motions',
  'Recently released AI email personalization features',
  'Expand automation across full sales cycle',
  'Strong focus on SDR team efficiency and pipeline generation'
),
(
  'Michael Chen',
  'Outreach',
  'Director of Revenue Operations',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Revenue operations platform for enterprise sales teams',
  'Sales execution platform with pipeline forecasting and coaching',
  'Unify sales execution and revenue intelligence in one platform',
  'Enterprise SaaS companies with complex sales cycles',
  'Launched new deal inspection dashboards for CROs',
  'Deepen RevOps integrations across CRM stack',
  'Prioritizing scalable processes and data-driven sales management'
),
(
  'Sarah Kim',
  'Gong',
  'Head of Customer Success',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'AI'],
  'Conversation intelligence platform for sales organizations',
  'AI-driven call analysis and deal intelligence platform',
  'Surface insights from every customer interaction to improve win rates',
  'B2B sales teams in SaaS and tech verticals',
  'Added real-time coaching alerts during live calls',
  'Grow enterprise segment with focus on call analytics',
  'Heavy investment in AI feature development and CS expansion'
),
(
  'James Wilson',
  'Clari',
  'VP of Sales',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Revenue platform for enterprise pipeline management and forecasting',
  'AI-powered revenue forecasting and pipeline management tool',
  'Give revenue leaders accurate forecasts and deal predictability',
  'Enterprise companies with multi-segment sales organizations',
  'Released new revenue waterfall analytics for CROs',
  'Build enterprise-grade forecasting capabilities',
  'Focus on accuracy of revenue prediction and deal progression tracking'
),
(
  'Olivia Martinez',
  'LinkedIn Sales Navigator',
  'Enterprise Account Executive',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Sales intelligence platform leveraging LinkedIn professional network',
  'Social selling platform with advanced prospecting and account insights',
  'Identify the right buyers and engage them with contextual outreach',
  'Enterprise sales teams targeting senior decision-makers',
  'Integrated new AI account recommendations engine',
  'Deepen CRM integrations and workflow automation',
  'Focused on helping enterprise teams build pipeline with warm signals'
),
(
  'Ethan Brown',
  'ZoomInfo',
  'Head of Growth',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'B2B data intelligence and go-to-market platform',
  'Contact and company data platform with intent signals and enrichment',
  'Fuel pipeline generation with accurate and actionable buyer data',
  'Sales and marketing teams at growth-stage and enterprise companies',
  'Launched buyer intent data enhancement with technographics',
  'Expand data coverage and accuracy in international markets',
  'Investing heavily in data quality and GTM intelligence tools'
),
(
  'Ava Johnson',
  'Seismic',
  'Director of Sales Enablement',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Sales enablement platform for content management and coaching',
  'Content intelligence platform for sales and marketing alignment',
  'Ensure every rep has the right content for every selling situation',
  'Enterprise B2B companies with large distributed sales teams',
  'Released AI-powered content recommendation engine',
  'Scale enablement programs across global sales force',
  'Focused on connecting enablement efforts to revenue outcomes'
),
(
  'Noah Davis',
  'Highspot',
  'VP of Revenue Enablement',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Revenue enablement platform connecting strategy to execution',
  'End-to-end sales enablement platform with analytics and training',
  'Bridge the gap between sales strategy and field execution',
  'Enterprise sales and marketing organizations',
  'Rolled out new scorecards for rep skill assessment',
  'Expand beyond content management into full sales performance suite',
  'Investing in AI-driven coaching and enablement analytics'
),
(
  'Sophia Lee',
  'Mindtickle',
  'Chief Revenue Officer',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Revenue productivity platform for sales readiness and coaching',
  'Sales readiness platform combining training, coaching, and analytics',
  'Build a consistently high-performing sales force through data-driven development',
  'Mid-market and enterprise B2B sales organizations',
  'Launched manager coaching dashboards with AI recommendations',
  'Grow into enterprise segment with advanced readiness analytics',
  'Focused on connecting enablement investment to quota attainment'
),
(
  'Liam Anderson',
  'Xactly',
  'Director of Sales Performance',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Intelligent revenue performance management platform',
  'Incentive compensation and sales planning platform with analytics',
  'Align sales behaviors with business outcomes through smart compensation design',
  'Enterprise companies managing complex variable compensation programs',
  'Released new quota-setting benchmarks using market data',
  'Expand into territory planning and headcount analytics',
  'Investing in cross-functional RevOps tools beyond compensation management'
),
(
  'Mia Taylor',
  'Groove',
  'Head of Sales Development',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Sales engagement platform purpose-built for Salesforce users',
  'Native Salesforce sales engagement platform for managing outbound workflows',
  'Eliminate CRM friction so reps spend more time selling',
  'Salesforce-centric mid-market sales teams',
  'Launched new flow automation builder for SDR workflows',
  'Deepen Salesforce-native capabilities and expand to enterprise',
  'Focused on reducing time-to-pipeline for sales development reps'
),
(
  'William Thomas',
  'Apollo.io',
  'VP of Sales Growth',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'SMB'],
  'All-in-one sales intelligence and engagement platform',
  'Prospecting and outreach platform combining data, sequencing, and analytics',
  'Give smaller teams enterprise-grade sales tools at accessible price points',
  'SMB and mid-market companies building outbound sales programs',
  'Expanded contact database to over 200 million verified records',
  'Scale upmarket while maintaining SMB value proposition',
  'Investing in data enrichment and AI-guided outreach personalization'
),
(
  'Charlotte Jackson',
  'Mediafly',
  'Director of Sales Productivity',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Revenue enablement and content management platform',
  'Sales content and analytics platform for buyer engagement tracking',
  'Understand exactly how buyers engage with content to accelerate deals',
  'Enterprise B2B sales teams with complex buying cycles',
  'Integrated new buyer engagement scoring into CRM workflows',
  'Expand from content management to full revenue enablement suite',
  'Focused on connecting content analytics to deal outcomes'
),
(
  'Benjamin White',
  'Showpad',
  'VP of Commercial Sales',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Sales enablement platform for training and content delivery',
  'Unified sales enablement platform for coaching, content, and buyer experience',
  'Enable sales teams to deliver compelling and personalized buyer experiences',
  'Enterprise teams in manufacturing, finance, and tech verticals',
  'Launched new digital sales room feature for remote selling',
  'Deepen buyer engagement analytics and expand international presence',
  'Investing in hybrid selling use cases and digital room capabilities'
),
(
  'Amelia Harris',
  'Brainshark',
  'Head of Sales Training',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Sales readiness platform focused on onboarding and continuous learning',
  'On-demand training and coaching platform with video-based assessments',
  'Reduce ramp time for new hires and build long-term rep competency',
  'Enterprise sales organizations with high headcount growth',
  'Released AI-powered video coaching feedback tool',
  'Expand from onboarding into ongoing skill development programs',
  'Strong focus on measurable ROI from sales training investments'
),
(
  'Lucas Martin',
  'Salescycle',
  'Head of Inside Sales',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Behavioral marketing and retargeting platform for sales conversion',
  'Real-time behavioral data platform that triggers personalized follow-ups',
  'Recover abandoned pipeline by engaging prospects at the right moment',
  'E-commerce and B2B companies with high-volume lead flows',
  'Launched new real-time intent triggers for sales team alerts',
  'Expand into mid-market with self-serve onboarding',
  'Focused on bridging marketing automation with sales outreach'
),
(
  'Isabella Garcia',
  'Chorus AI',
  'Director of Conversation Intelligence',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'AI'],
  'Conversation intelligence platform for revenue teams',
  'AI call recording and analysis platform with coaching and deal insights',
  'Extract actionable deal insights from every sales conversation',
  'Revenue teams in SaaS and professional services',
  'Rolled out competitive intelligence alerts from call transcripts',
  'Expand real-time coaching features during live calls',
  'Investing in AI capabilities and CRM-native deal intelligence'
),
(
  'Henry Martinez',
  'Kluster',
  'Head of Revenue Analytics',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Revenue forecasting and analytics platform for B2B sales teams',
  'Predictive sales forecasting platform with scenario modeling',
  'Give RevOps teams accurate and explainable pipeline forecasting',
  'Mid-market SaaS companies looking to move beyond spreadsheet forecasting',
  'Released new what-if scenario builder for forecast planning',
  'Grow customer base in RevOps-centric organizations',
  'Focused on pipeline quality metrics and forecast confidence scoring'
),
(
  'Evelyn Robinson',
  'Jiminny',
  'VP of Sales',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Conversation intelligence and sales coaching platform',
  'Team collaboration and coaching platform integrated with call analytics',
  'Help sales managers coach their teams through data-backed conversations',
  'Mid-market B2B SaaS companies with growing sales teams',
  'Launched Slack integration for real-time deal alerts',
  'Expand from coaching into full revenue intelligence suite',
  'Investing in team collaboration features alongside call analytics'
),
(
  'Alexander Clark',
  'Troops',
  'Director of Revenue Intelligence',
  'Sales Technology',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Revenue signals platform connecting Salesforce to Slack',
  'Slack-native sales alerts and CRM automation platform',
  'Bring real-time deal signals and CRM updates to where teams work',
  'Sales and RevOps teams using Salesforce and Slack together',
  'Integrated new AI-generated deal summaries in Slack notifications',
  'Expand workflow automation beyond Salesforce to other GTM tools',
  'Focused on meeting sales teams in their existing communication workflows'
),
(
  'Grace Thompson',
  'Klaviyo',
  'Director of Demand Generation',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Data-driven marketing automation platform for e-commerce brands',
  'Email and SMS marketing platform with predictive analytics and segmentation',
  'Help brands grow revenue through highly personalized customer journeys',
  'E-commerce and DTC brands managing large customer databases',
  'Launched new predictive customer lifetime value segmentation',
  'Expand B2B product offering alongside core e-commerce focus',
  'Investing in data unification and advanced segmentation capabilities'
),
(
  'Daniel Lewis',
  'Braze',
  'VP of Marketing Technology',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Customer engagement platform for multi-channel lifecycle marketing',
  'Cross-channel customer engagement platform with real-time messaging',
  'Deliver highly contextual messages at scale across web, mobile, and email',
  'Enterprise consumer and B2B brands with mobile-first audiences',
  'Released new canvas builder for complex multi-step customer journeys',
  'Grow in financial services and healthcare verticals',
  'Focused on real-time data activation and personalization at enterprise scale'
),
(
  'Chloe Walker',
  'ActiveCampaign',
  'Head of CRM Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'SMB'],
  'Marketing automation and CRM platform for small businesses',
  'All-in-one email marketing and automation platform with CRM',
  'Help small businesses grow customer relationships with simple but powerful automation',
  'Small businesses and agencies managing customer communications',
  'Launched new AI email content generator for campaigns',
  'Deepen CRM and sales automation capabilities',
  'Focused on ease of use and quick time-to-value for SMB customers'
),
(
  'Matthew Hall',
  'Iterable',
  'Director of Growth Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Growth marketing platform for data-driven lifecycle campaigns',
  'Cross-channel marketing automation platform with advanced audience segmentation',
  'Enable growth marketers to run sophisticated lifecycle programs without engineering bottlenecks',
  'Mid-market and enterprise companies with data-rich customer bases',
  'Released new AI-powered send-time optimization feature',
  'Expand into mid-market with more accessible pricing tiers',
  'Focused on reducing time-to-launch for complex multi-channel campaigns'
),
(
  'Hannah Allen',
  'Customer.io',
  'Head of Lifecycle Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Behavioral messaging platform for SaaS and tech companies',
  'Behavior-driven messaging platform for email, push, and SMS campaigns',
  'Turn real-time user actions into automated, personalized communications',
  'SaaS product teams and growth marketers managing user lifecycle',
  'Launched new in-app messaging channel with event-triggered flows',
  'Expand data sources and integrations with product analytics tools',
  'Focused on connecting product usage data to marketing messaging'
),
(
  'Christopher Young',
  'Omnisend',
  'VP of E-commerce Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2C', 'SMB'],
  'E-commerce marketing automation platform for omnichannel campaigns',
  'Email and SMS automation platform built specifically for e-commerce',
  'Help online stores recover revenue with automated retention campaigns',
  'Small and mid-sized e-commerce merchants on Shopify and WooCommerce',
  'Launched new pre-built automation workflows for cart abandonment',
  'Grow market share in mid-market e-commerce segment',
  'Focused on making advanced automation accessible without technical expertise'
),
(
  'Samantha Hernandez',
  'Intercom',
  'Director of Conversational Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Conversational relationship platform for marketing and support',
  'Chat-based marketing automation with AI-powered lead qualification',
  'Convert website visitors into qualified pipeline through intelligent conversations',
  'B2B SaaS companies looking to reduce reliance on form-based conversion',
  'Released new AI agent builder for autonomous visitor qualification',
  'Expand from support-focused use cases into full marketing suite',
  'Investing in proactive engagement and AI-driven conversation automation'
),
(
  'Ryan King',
  'Drip',
  'Head of Email Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2C', 'SMB'],
  'E-commerce CRM and email marketing platform',
  'Automated email marketing platform with deep e-commerce integrations',
  'Help online brands build lasting customer relationships through smart automation',
  'DTC e-commerce brands growing past initial acquisition phase',
  'Integrated new post-purchase behavior triggers for win-back flows',
  'Expand into SMS and push notification channels',
  'Focused on retention marketing for e-commerce merchants'
),
(
  'Victoria Wright',
  'Pardot',
  'Director of B2B Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Salesforce-native B2B marketing automation platform',
  'B2B marketing automation platform with native Salesforce integration',
  'Align marketing and sales teams on a single platform for lead management',
  'Enterprise B2B companies heavily invested in the Salesforce ecosystem',
  'Launched new Einstein AI lead scoring improvements',
  'Deepen cross-cloud integrations within Salesforce platform',
  'Focused on enterprise account-based marketing and pipeline attribution'
),
(
  'Nathan Scott',
  'Marketo Engage',
  'Head of Demand Generation',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Enterprise marketing automation platform for B2B demand generation',
  'Comprehensive B2B marketing platform with lead management and analytics',
  'Drive pipeline velocity and revenue attribution across complex buying journeys',
  'Enterprise marketing teams in technology, financial services, and healthcare',
  'Released new AI-assisted content recommendations for nurture streams',
  'Expand account-based marketing capabilities and tighten Salesforce sync',
  'Focused on proving marketing contribution to pipeline and closed revenue'
),
(
  'Emily Green',
  'Mailchimp',
  'VP of SMB Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2C', 'SMB'],
  'All-in-one marketing platform for small businesses',
  'Email marketing and basic automation platform with e-commerce tools',
  'Provide an accessible entry point for small businesses to start marketing automation',
  'Early-stage small businesses and solopreneurs launching digital marketing',
  'Released AI-assisted email campaign builder with template suggestions',
  'Expand into more robust marketing automation beyond email',
  'Focused on simplicity and quick activation for non-technical users'
),
(
  'Brandon Adams',
  'Sailthru',
  'Director of Personalization',
  'Marketing Automation',
  ARRAY['SaaS', 'B2C', 'Enterprise'],
  'AI-driven personalization and omnichannel marketing platform',
  'Predictive personalization platform for email, web, and mobile messaging',
  'Deliver individually relevant experiences at scale to reduce churn and grow LTV',
  'Retail, media, and publishing companies managing large subscriber audiences',
  'Launched new predictive send optimization with individual-level modeling',
  'Expand into additional digital channels and international markets',
  'Heavy investment in AI personalization and cross-channel coordination'
),
(
  'Stephanie Baker',
  'Acoustic',
  'Chief Marketing Officer',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Enterprise marketing cloud for campaign management and analytics',
  'Multi-channel campaign management platform with deep analytics',
  'Enable large marketing teams to coordinate complex cross-channel campaigns',
  'Enterprise companies with diverse digital marketing operations',
  'Released new marketing attribution dashboards with multi-touch modeling',
  'Modernize platform capabilities to compete with cloud-native alternatives',
  'Focused on proving ROI and marketing effectiveness across campaigns'
),
(
  'Tyler Gonzalez',
  'HubSpot Marketing Hub',
  'Director of Inbound Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'All-in-one inbound marketing and automation platform',
  'Integrated marketing platform with CMS, email, social, and analytics',
  'Attract, engage, and convert leads through inbound methodology',
  'Growing B2B companies looking for a unified marketing and sales platform',
  'Launched new AI blog and social post generation assistant',
  'Expand enterprise product capabilities and improve reporting depth',
  'Focused on making sophisticated marketing accessible to lean teams'
),
(
  'Rachel Nelson',
  'Sendinblue',
  'Head of Digital Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'SMB'],
  'All-in-one digital marketing platform with email, SMS, and CRM',
  'Integrated marketing communication suite for growing businesses',
  'Give businesses a cost-effective platform to manage all customer communications',
  'SMB companies in Europe and emerging markets',
  'Released new transactional email API with improved deliverability',
  'Expand into full CRM and marketing automation for mid-market',
  'Focused on deliverability, pricing accessibility, and ease of integration'
),
(
  'Jordan Carter',
  'Segment',
  'VP of Marketing Data',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Customer data platform for marketing and product teams',
  'CDP platform for collecting, unifying, and activating customer data',
  'Give marketing teams a single source of truth for customer behavior',
  'High-growth B2B and B2C companies managing fragmented data stacks',
  'Launched new reverse ETL capabilities for data warehouse activation',
  'Expand use cases beyond data collection into marketing orchestration',
  'Focused on data quality and activation across all marketing channels'
),
(
  'Morgan Perez',
  'Encharge',
  'Head of SaaS Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'SMB'],
  'Behavior-based email marketing automation for SaaS companies',
  'Event-driven email automation platform purpose-built for SaaS onboarding and retention',
  'Help SaaS companies reduce churn through automated lifecycle messaging tied to product usage',
  'Early-stage and growth-stage SaaS companies',
  'Launched new trial conversion automation templates',
  'Grow customer base among bootstrapped and early-stage SaaS founders',
  'Focused on product-led growth scenarios and usage-based triggers'
),
(
  'Austin Roberts',
  'MoEngage',
  'Director of Customer Engagement',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Insights-led customer engagement platform',
  'AI-powered omnichannel marketing platform for mobile and web',
  'Personalize customer journeys across every digital touchpoint in real time',
  'Consumer apps and e-commerce companies in high-growth markets',
  'Released new AI-powered funnel drop-off recovery campaign builder',
  'Expand geographically into Southeast Asia and LATAM markets',
  'Focused on mobile-first engagement and retention optimization'
),
(
  'Kayla Turner',
  'Leanplum',
  'VP of Mobile Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2C', 'Mid-Market'],
  'Mobile marketing automation platform for engagement and retention',
  'Mobile A/B testing and campaign automation platform',
  'Optimize in-app messaging and push notifications through continuous experimentation',
  'Mobile apps in gaming, fintech, and consumer media verticals',
  'Launched new predictive churn model for proactive re-engagement',
  'Deepen integration with analytics platforms and attribution tools',
  'Focused on mobile-native experiences and rapid experimentation cycles'
),
(
  'Derrick Phillips',
  'Vero',
  'Head of Product Marketing',
  'Marketing Automation',
  ARRAY['SaaS', 'B2B', 'SMB'],
  'Event-driven email and push notification platform',
  'API-first messaging platform for transactional and behavioral campaigns',
  'Enable developers and marketers to build highly targeted messaging without complex infrastructure',
  'SaaS and app companies needing developer-friendly messaging tools',
  'Released new no-code workflow builder for non-technical marketers',
  'Expand from developer-first positioning toward product-marketer audience',
  'Focused on bridging technical flexibility with marketer-friendly usability'
),
(
  'Raj Patel',
  'Scale AI',
  'Director of ML Engineering',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Data labeling and AI development platform for enterprise ML teams',
  'AI data platform for training data creation, model evaluation, and RLHF',
  'Accelerate AI model development with high-quality training data at scale',
  'Enterprise companies and government agencies building proprietary AI models',
  'Launched new RLHF pipeline for LLM fine-tuning workflows',
  'Expand into model evaluation and AI safety benchmarking',
  'Focused on becoming the foundational layer for enterprise AI development'
),
(
  'Priya Sharma',
  'Cohere',
  'Head of Enterprise AI',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Enterprise NLP and generative AI platform',
  'Large language model API platform with enterprise security and deployment options',
  'Give enterprises access to powerful NLP models with control over data privacy',
  'Enterprises in finance, legal, and healthcare needing secure AI deployment',
  'Launched new command model optimized for enterprise search and summarization',
  'Expand into on-premise and private cloud deployment options',
  'Focused on trust, security, and regulatory compliance for enterprise AI'
),
(
  'David Kim',
  'Hugging Face',
  'VP of ML Solutions',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Open-source AI model hub and enterprise ML platform',
  'Collaborative ML platform for hosting, fine-tuning, and deploying AI models',
  'Lower the barrier to deploying state-of-the-art AI through open-source tooling',
  'ML teams at startups and enterprises who prefer open-source AI infrastructure',
  'Launched Inference Endpoints for one-click model deployment',
  'Grow enterprise product while maintaining community-first strategy',
  'Investing heavily in enterprise features on top of open-source foundation'
),
(
  'Lisa Chen',
  'Databricks',
  'Director of AI Platform',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Unified data and AI platform for analytics and machine learning',
  'Lakehouse platform combining data engineering, analytics, and AI model training',
  'Unify data and AI workflows on a single platform to reduce infrastructure complexity',
  'Enterprise data and ML teams at large-scale organizations',
  'Released new AI Gateway for managing LLM usage and costs',
  'Expand beyond data engineering into full AI lifecycle management',
  'Focused on consolidating data and AI workloads to reduce tool sprawl'
),
(
  'James Nguyen',
  'H2O.ai',
  'Head of AutoML',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Open-source and enterprise AutoML and ML operations platform',
  'AutoML platform for building, deploying, and monitoring predictive models',
  'Enable data science teams to build production-ready models faster with automated ML',
  'Enterprise data science teams in finance, insurance, and telecom',
  'Launched new LLM fine-tuning capabilities alongside core AutoML product',
  'Expand into generative AI alongside predictive ML focus',
  'Focused on democratizing ML across business analysts and data scientists'
),
(
  'Sandra Williams',
  'Weights and Biases',
  'Director of ML Infrastructure',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'MLOps and experiment tracking platform for ML teams',
  'Developer-first MLOps platform for experiment tracking, model registry, and pipeline management',
  'Give ML engineers the tools to build better models faster through systematic experimentation',
  'ML teams at research labs, startups, and mid-market tech companies',
  'Launched new LLM evaluation and fine-tuning tracking features',
  'Expand into larger enterprise segment with governance and compliance features',
  'Focused on developer experience and reducing friction in the ML development lifecycle'
),
(
  'Carlos Rivera',
  'DataRobot',
  'VP of AI Solutions',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Enterprise AI platform for automated model building and deployment',
  'End-to-end AI platform automating model development, governance, and monitoring',
  'Reduce the time from data to deployed AI model from months to days',
  'Enterprise organizations in banking, insurance, and manufacturing',
  'Released new AI governance and explainability dashboard for compliance',
  'Expand from predictive AI into generative AI use cases',
  'Focused on responsible AI deployment with strong audit and monitoring capabilities'
),
(
  'Jessica Park',
  'Alteryx',
  'Head of Analytics Automation',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Analytics automation platform for data preparation and ML',
  'Self-service analytics and ML platform for business analysts',
  'Enable non-technical business users to build and run sophisticated data workflows',
  'Enterprises in retail, finance, and healthcare relying on spreadsheet-heavy analytics',
  'Launched new cloud-native version with expanded AutoML capabilities',
  'Grow cloud adoption among on-premise installed base',
  'Focused on bringing AI capabilities to line-of-business users without data science backgrounds'
),
(
  'Kevin Brooks',
  'Domino Data Lab',
  'Director of Data Science',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Enterprise MLOps platform for data science teams at scale',
  'Collaborative model development and deployment platform for enterprise data science',
  'Enable distributed data science teams to work faster with reproducible and governed workflows',
  'Large enterprise companies with mature data science organizations',
  'Released new GPU cluster management for LLM training workloads',
  'Expand use cases from predictive modeling into generative AI',
  'Focused on governance, reproducibility, and auditability of ML workflows'
),
(
  'Tara Mitchell',
  'Vertex AI',
  'Enterprise AI Solutions Lead',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Google Cloud managed ML platform for enterprise AI development',
  'Fully managed ML platform with model training, deployment, and monitoring',
  'Provide enterprises with scalable and governed AI infrastructure backed by Google research',
  'Enterprise engineering and data teams building production AI applications',
  'Launched new Model Garden with access to foundation models including Gemini',
  'Grow adoption among non-Google-native enterprises',
  'Focused on reducing operational burden of ML infrastructure management'
),
(
  'Aisha Thompson',
  'Verta AI',
  'Head of Model Management',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Model management and deployment platform for ML engineering teams',
  'MLOps platform for model versioning, experimentation, and deployment',
  'Help ML teams take models from experiment to production with less overhead',
  'Mid-market tech companies with growing ML teams',
  'Released new integrations with major ML frameworks and cloud providers',
  'Expand governance features for regulated industry use cases',
  'Focused on bridging the gap between research and production ML'
),
(
  'Marcus Johnson',
  'Algorithmia',
  'VP of MLOps',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'MLOps and model deployment platform for enterprise AI',
  'Enterprise model deployment and serving platform with governance and versioning',
  'Standardize and operationalize AI model deployment across the enterprise',
  'Large organizations with many models in production needing centralized management',
  'Launched new monitoring dashboard for production model drift detection',
  'Expand governance features to support regulated industry requirements',
  'Focused on model lifecycle management and reducing deployment risk'
),
(
  'Nina Patel',
  'Tecton',
  'Head of Feature Engineering',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Enterprise feature platform for real-time ML',
  'Feature store and pipeline platform for operationalizing ML features',
  'Give ML teams a reliable way to build, share, and serve features in production',
  'Data-driven tech companies building real-time recommendation and fraud detection systems',
  'Released new streaming feature pipeline with sub-second latency',
  'Expand platform to support batch and real-time features in unified interface',
  'Focused on reducing feature engineering toil and accelerating model iteration'
),
(
  'Owen Davis',
  'Labelbox',
  'Director of Training Data',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Training data platform for AI model development',
  'Data annotation and labeling platform with quality management and collaboration',
  'Enable AI teams to create, manage, and improve training datasets at scale',
  'Enterprise AI teams building computer vision, NLP, and multimodal models',
  'Launched new LLM evaluation and human feedback workflows',
  'Expand into model evaluation beyond training data creation',
  'Focused on human-in-the-loop AI development workflows'
),
(
  'Felix Zhang',
  'Snorkel AI',
  'VP of AI Development',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Programmatic data labeling and AI development platform',
  'Data-centric AI platform using programmatic labeling and weak supervision',
  'Dramatically reduce the cost and time of building high-quality training datasets',
  'Enterprises building domain-specific AI models in healthcare, finance, and legal',
  'Launched new fine-tuning workflows for large language models',
  'Expand from NLP into multimodal AI model development',
  'Focused on reducing dependency on expensive manual data labeling'
),
(
  'Priya Gupta',
  'Clarifai',
  'Director of Vision AI',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Full-stack AI platform for computer vision and NLP',
  'End-to-end AI platform covering labeling, training, deployment, and monitoring',
  'Provide a single platform for building and deploying custom vision and language models',
  'Enterprises in retail, manufacturing, and media building visual AI applications',
  'Released new foundation model fine-tuning with minimal labeled data',
  'Expand from visual AI into multi-modal model capabilities',
  'Focused on making AI model development accessible to domain experts'
),
(
  'Aaron Lee',
  'Seldon',
  'Head of ML Deployment',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Open-source and enterprise ML deployment and monitoring platform',
  'Model serving and monitoring platform for production ML inference',
  'Ensure reliable and observable ML model deployment in production environments',
  'Enterprise ML engineering teams managing large numbers of production models',
  'Launched new drift detection and explainability modules for compliance',
  'Expand into cloud-agnostic ML infrastructure for regulated sectors',
  'Focused on production reliability and ML observability'
),
(
  'Diana Flores',
  'Fiddler AI',
  'VP of ML Observability',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'AI observability and model monitoring platform',
  'Model performance monitoring and explainability platform for production AI',
  'Give ML teams visibility into how models behave in production to prevent failures',
  'Enterprises in finance, insurance, and healthcare with regulated AI deployments',
  'Released new LLM monitoring capabilities for generative AI applications',
  'Expand from predictive model monitoring into full AI observability',
  'Focused on explainability, fairness, and compliance in production AI'
),
(
  'Tariq Hassan',
  'Arize AI',
  'Director of Model Performance',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'ML observability platform for model performance monitoring',
  'Model monitoring and troubleshooting platform with embedding visualization',
  'Surface and resolve model performance issues before they impact the business',
  'ML teams at tech companies with models in production',
  'Released new LLM tracing and evaluation for generative AI use cases',
  'Expand customer base beyond ML-native companies to broader enterprise',
  'Focused on reducing time-to-detection for model degradation'
),
(
  'Leila Nouri',
  'Dataiku',
  'Chief Data Scientist',
  'AI / ML Platforms',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Collaborative AI and analytics platform for enterprise data teams',
  'Enterprise AI platform for data preparation, model building, and deployment',
  'Enable diverse teams of data scientists, analysts, and engineers to collaborate on AI projects',
  'Large enterprises in banking, insurance, telecom, and manufacturing',
  'Launched new LLM capabilities integrated into existing data science workflows',
  'Expand into generative AI use cases while growing core predictive AI platform',
  'Focused on democratizing AI across the enterprise with strong governance'
),
(
  'Robert Lee',
  'Stripe',
  'VP of Platform Partnerships',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Developer-first payments infrastructure platform',
  'Global payments and financial infrastructure for internet businesses',
  'Enable businesses to accept payments, manage subscriptions, and issue cards through unified APIs',
  'Internet businesses from startups to global enterprises needing reliable payment infrastructure',
  'Launched new Stripe Tax for automated global tax calculation',
  'Expand financial services offering beyond core payments',
  'Focused on becoming the complete financial operating system for businesses'
),
(
  'Jennifer Garcia',
  'Plaid',
  'Director of Financial Data',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'API'],
  'Open banking API platform for financial data connectivity',
  'Financial data network connecting apps to users bank accounts',
  'Enable fintech applications to access and verify user financial data securely',
  'Fintech apps, lending platforms, and PFM tools building data-driven financial products',
  'Released new income and identity verification products',
  'Expand international footprint beyond North America',
  'Focused on trust, privacy, and compliance in financial data access'
),
(
  'Thomas Brown',
  'Marqeta',
  'Head of Issuer Processing',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Modern card issuing platform for fintech and enterprise',
  'API-based card issuing and payment processing platform',
  'Enable companies to build differentiated card programs with fine-grained transaction controls',
  'Fintech companies, challenger banks, and enterprises building card-based financial products',
  'Launched new instant card issuance for digital wallet programs',
  'Expand beyond North America into European card markets',
  'Focused on enabling real-time spending controls and program customization'
),
(
  'Patricia Wilson',
  'Brex',
  'VP of Finance Products',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Corporate cards and spend management platform',
  'Integrated corporate card, expense management, and banking platform',
  'Automate financial operations and give finance teams real-time visibility into company spending',
  'Startups and enterprise companies managing high-growth financial operations',
  'Released new AI expense categorization and policy enforcement',
  'Expand global expense management capabilities for distributed teams',
  'Focused on replacing legacy expense management with integrated financial stack'
),
(
  'Kevin Martinez',
  'Adyen',
  'Director of Enterprise Payments',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Unified commerce payments platform for global enterprises',
  'Global payment processing platform with acquiring, processing, and risk management',
  'Unify payment acceptance across online, in-store, and mobile channels for global enterprises',
  'Enterprise retail, hospitality, and marketplace companies with complex payment needs',
  'Launched new unified commerce features for omnichannel payment data',
  'Expand into embedded finance products for platforms',
  'Focused on helping enterprises reduce payment complexity and improve authorization rates'
),
(
  'Elizabeth Taylor',
  'Modern Treasury',
  'Head of Payment Operations',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'API'],
  'Payment operations platform for businesses moving money at scale',
  'Programmable payments and money movement infrastructure via API',
  'Enable finance and engineering teams to automate complex multi-bank payment workflows',
  'Companies in lending, real estate, and marketplaces managing high-volume bank transfers',
  'Launched new reconciliation automation with bank statement matching',
  'Expand use cases into embedded finance and payment operations outsourcing',
  'Focused on reducing manual work in payment operations through automation'
),
(
  'Samuel Anderson',
  'Codat',
  'Director of Financial API',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'API'],
  'Universal API platform for business financial data',
  'API layer connecting fintech products to SMB accounting and banking data',
  'Enable financial services companies to build data-driven products for SMBs without custom integrations',
  'Lenders, payment providers, and software companies serving SMB market',
  'Launched new cash flow analytics product for underwriting use cases',
  'Expand coverage of banking and ERP integrations globally',
  'Focused on reducing integration complexity for fintech builders'
),
(
  'Rachel Scott',
  'Rapyd',
  'VP of Global Payments',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Global fintech-as-a-service platform for payments and payouts',
  'All-in-one payment platform with local payment methods, issuing, and wallets',
  'Give businesses one integration to accept and send money in any country',
  'Marketplace platforms, gig economy companies, and global e-commerce players',
  'Launched new embedded wallet product for platform payout programs',
  'Expand local payment method coverage in Southeast Asia and Africa',
  'Focused on enabling global financial operations through a single API'
),
(
  'Christopher Evans',
  'Payoneer',
  'Head of Marketplace Payments',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Marketplace'],
  'Global payment platform for marketplaces and SMBs',
  'Cross-border payment and working capital platform for global sellers and service providers',
  'Help businesses receive payments from global customers and access working capital',
  'Freelancers, marketplaces, and SMBs doing cross-border business',
  'Launched new working capital product for marketplace sellers',
  'Expand into banking-as-a-service for platform partners',
  'Focused on financial empowerment for global commerce participants'
),
(
  'Jessica Young',
  'Tipalti',
  'Director of AP Automation',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Global payables automation platform',
  'End-to-end accounts payable automation platform for global supplier payments',
  'Automate global payment operations, reduce fraud risk, and ensure tax compliance',
  'Mid-market and enterprise companies making high-volume international supplier payments',
  'Released new AI-powered invoice processing with dynamic discounting',
  'Expand into procurement and spend management adjacent to core payables',
  'Focused on reducing financial operations overhead for global businesses'
),
(
  'Brian Harris',
  'Ramp',
  'VP of Finance Automation',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Corporate finance automation platform',
  'Corporate card and expense platform with AI-driven spend intelligence',
  'Help finance teams control spend and close books faster through automation',
  'Mid-market companies looking to modernize finance operations',
  'Launched new vendor management and negotiation intelligence features',
  'Expand enterprise capabilities and financial services product suite',
  'Focused on generating measurable savings through spend optimization'
),
(
  'Amanda Clark',
  'Navan',
  'Head of Travel and Expense',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Corporate travel and expense management platform',
  'Integrated travel booking and expense management platform with real-time policy controls',
  'Consolidate business travel and expense management into one user-friendly platform',
  'Enterprises managing significant employee travel and expense programs',
  'Released new AI itinerary builder for personalized travel recommendations',
  'Expand internationally and grow SMB segment alongside enterprise base',
  'Focused on improving traveler experience while maintaining compliance and cost control'
),
(
  'Daniel Robinson',
  'Unit',
  'Director of Embedded Banking',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Banking-as-a-service platform for embedding financial products',
  'API-first BaaS platform for launching bank accounts, cards, and payments',
  'Enable software companies to embed financial products without building banking infrastructure',
  'SaaS companies, marketplaces, and consumer apps adding financial features',
  'Launched new credit product API for embedded lending',
  'Expand compliance coverage for regulated industry partners',
  'Focused on making embedded finance accessible to non-financial companies'
),
(
  'Melissa White',
  'Checkout.com',
  'VP of Payment Optimization',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Enterprise payment processing platform with intelligent routing',
  'Full-stack payments platform with network tokens, risk management, and analytics',
  'Maximize payment acceptance rates while minimizing fraud and processing costs',
  'Enterprise e-commerce, gaming, and subscription companies with high payment volume',
  'Launched new network tokenization for improved card-not-present approval rates',
  'Expand geographical payment processing coverage in high-growth markets',
  'Focused on payment performance optimization through data and intelligent routing'
),
(
  'George Thompson',
  'Treasury Prime',
  'Head of Banking APIs',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'API'],
  'Banking API platform connecting fintech to community banks',
  'Middleware layer connecting fintech developers to sponsor bank APIs',
  'Enable fintech startups to launch compliant banking products without direct bank relationships',
  'Fintech companies needing access to FDIC-insured banking rails quickly',
  'Launched new integrated onboarding flow with partner bank network',
  'Expand bank partner network for more product flexibility',
  'Focused on reducing time-to-launch for embedded banking products'
),
(
  'Christine Lewis',
  'Synapse',
  'Director of Financial Infrastructure',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Banking-as-a-service platform for fintech companies',
  'API platform for banking, lending, and brokerage infrastructure',
  'Give fintech builders fast access to regulated financial infrastructure without bank charters',
  'Early and growth-stage fintech companies building consumer financial products',
  'Launched new savings account API with competitive interest rate programs',
  'Expand partner banking relationships to improve product coverage',
  'Focused on developer experience and rapid product iteration for fintech builders'
),
(
  'Andrew Johnson',
  'Sift',
  'Head of Fraud Prevention',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Digital trust and safety platform for fraud prevention',
  'Machine learning fraud detection and prevention platform for payments and accounts',
  'Stop fraud losses while minimizing friction for legitimate customers',
  'E-commerce, fintech, and marketplace companies with significant fraud exposure',
  'Launched new account takeover detection with behavioral biometrics',
  'Expand into new fraud vectors including buy-now-pay-later and crypto',
  'Focused on reducing false positives that hurt good customer conversion'
),
(
  'Kimberly Davis',
  'Sardine',
  'VP of Compliance Technology',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Fraud and compliance platform for fintech companies',
  'Behavioral analytics and risk decisioning platform for KYC and fraud',
  'Help fintech companies detect and prevent fraud while passing compliance audits',
  'Fintech companies, crypto exchanges, and neobanks managing regulatory risk',
  'Launched new device intelligence features for onboarding fraud detection',
  'Expand into KYB and business identity verification',
  'Focused on helping high-growth fintech companies scale compliance without slowing down'
),
(
  'David Martinez',
  'Socure',
  'Director of Digital Identity',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'AI-powered digital identity verification platform',
  'Machine learning identity verification and fraud prevention platform',
  'Verify identity accurately at onboarding while stopping identity fraud in real time',
  'Banks, fintech companies, and government agencies managing identity verification',
  'Launched new graph-based document fraud detection',
  'Expand verification capabilities into global document types',
  'Focused on improving financial inclusion through more accurate identity verification'
),
(
  'Rebecca Brown',
  'Persona',
  'Head of Identity Operations',
  'Fintech',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Configurable identity platform for KYC and onboarding',
  'No-code identity verification and KYC orchestration platform',
  'Give operations and compliance teams the ability to build and adjust KYC flows without engineering',
  'Fintech, gaming, and marketplace companies with identity verification requirements',
  'Launched new reusable identity feature for returning user verification',
  'Expand into fraud orchestration beyond core identity verification',
  'Focused on reducing compliance team burden through configurable automated workflows'
),
(
  'Steven Park',
  'HashiCorp',
  'VP of Platform Engineering',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Infrastructure automation and security platform',
  'Cloud infrastructure automation platform with Terraform, Vault, and Consul',
  'Enable organizations to provision, secure, and connect cloud infrastructure through code',
  'Enterprise engineering teams managing complex multi-cloud infrastructure',
  'Launched HCP Terraform with expanded team collaboration features',
  'Expand managed cloud services alongside open-source tools',
  'Focused on making infrastructure as code the standard for enterprise cloud operations'
),
(
  'Lauren Kim',
  'Datadog',
  'Director of Observability',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Cloud-scale observability and monitoring platform',
  'Unified monitoring, APM, and logging platform for cloud infrastructure and applications',
  'Give engineering teams full observability into every layer of their infrastructure and applications',
  'Engineering and DevOps teams managing cloud-native applications at scale',
  'Launched new LLM observability product for AI application monitoring',
  'Expand platform coverage into security and developer experience',
  'Focused on becoming the single pane of glass for cloud engineering visibility'
),
(
  'Marcus Williams',
  'Grafana Labs',
  'Head of Infrastructure Monitoring',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Open-source observability and monitoring platform',
  'Composable observability platform for metrics, logs, traces, and dashboards',
  'Give engineering teams flexible, open-source monitoring without vendor lock-in',
  'Engineering teams who prefer open standards and tools with strong community support',
  'Launched new Grafana Cloud enterprise tier with enhanced SLAs',
  'Expand commercial offering while maintaining open-source community',
  'Focused on interoperability with Prometheus, OpenTelemetry, and cloud-native standards'
),
(
  'Natalie Johnson',
  'Pulumi',
  'VP of Cloud Engineering',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Infrastructure as code platform using general-purpose languages',
  'Modern IaC platform supporting Python, TypeScript, Go, and .NET',
  'Enable developers to manage cloud infrastructure using familiar programming languages',
  'Dev-first engineering teams building cloud infrastructure alongside application code',
  'Launched new AI assistant for infrastructure code generation and review',
  'Expand enterprise features including policy as code and audit logging',
  'Focused on bridging the gap between application and infrastructure development'
),
(
  'Ryan Thompson',
  'Terraform Cloud',
  'Director of IaC Operations',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Managed Terraform platform for collaborative infrastructure automation',
  'Hosted Terraform workspace management with run history and access controls',
  'Enable teams to collaborate on Terraform infrastructure safely at scale',
  'Enterprise engineering teams using Terraform for cloud infrastructure management',
  'Released new no-code resource provisioning for platform teams',
  'Expand self-service infrastructure portal for internal developer platforms',
  'Focused on making Terraform adoption scalable across large organizations'
),
(
  'Vanessa Davis',
  'Rancher Labs',
  'Head of Container Operations',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Enterprise Kubernetes management platform',
  'Container management platform for deploying and managing Kubernetes at enterprise scale',
  'Simplify Kubernetes adoption and operations for enterprise engineering teams',
  'Enterprises moving from VMs to container-based application deployment',
  'Launched new centralized policy management for multi-cluster environments',
  'Expand from infrastructure management into full developer platform',
  'Focused on reducing Kubernetes operational complexity for enterprise teams'
),
(
  'Patrick Moore',
  'Snyk',
  'VP of Developer Security',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Developer-first security platform for finding and fixing vulnerabilities',
  'Security tooling for developers covering code, containers, IaC, and open-source dependencies',
  'Embed security into the development workflow so vulnerabilities are caught before production',
  'Enterprise engineering teams adopting shift-left security practices',
  'Launched new DeepCode AI model for intelligent code vulnerability detection',
  'Expand platform coverage across full software supply chain security',
  'Focused on making security a developer experience problem rather than a security team problem'
),
(
  'Angela Chen',
  'PagerDuty',
  'Director of Incident Management',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Digital operations management and incident response platform',
  'Alert routing, on-call management, and incident response automation platform',
  'Reduce incident response time and operational noise through intelligent alert management',
  'DevOps and SRE teams managing high-availability production services',
  'Launched new AI-powered incident triage and runbook automation',
  'Expand from incident management into full AIOps platform',
  'Focused on reducing MTTR and improving operational resilience'
),
(
  'Derek Wilson',
  'New Relic',
  'Head of APM',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Full-stack observability platform for application and infrastructure monitoring',
  'Application performance monitoring platform with distributed tracing and error analytics',
  'Give engineering teams the context they need to ship reliable software faster',
  'Engineering teams managing microservices and distributed applications',
  'Launched new consumption-based pricing model to expand adoption',
  'Expand platform to support all telemetry types on single unified platform',
  'Focused on simplifying observability with all-in-one data ingest and analysis'
),
(
  'Sandra Robinson',
  'Dynatrace',
  'VP of AI Observability',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'AI-powered observability and security platform',
  'Unified observability platform with AI-driven root cause analysis and automation',
  'Automate monitoring and resolve problems before users are impacted',
  'Large enterprise IT and DevOps organizations with complex hybrid environments',
  'Launched new application security module integrated with runtime monitoring',
  'Expand into security observability as unified platform capability',
  'Focused on AI-driven automation to reduce manual operational work'
),
(
  'Carlos Thompson',
  'Cloudflare',
  'Director of Edge Infrastructure',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Global network and security platform for web applications',
  'Edge computing and network security platform with CDN, DDoS protection, and Zero Trust',
  'Protect and accelerate every web property through a global intelligence network',
  'Enterprises with global digital presence needing performance and security at the edge',
  'Launched new AI inference on the edge with Workers AI',
  'Expand into SASE and Zero Trust security for enterprise IT teams',
  'Focused on consolidating network performance and security on unified platform'
),
(
  'Michelle Garcia',
  'Fastly',
  'Head of Edge Delivery',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Edge cloud platform for fast and secure content delivery',
  'Programmable CDN and edge compute platform for real-time content delivery',
  'Give developers a fast, secure, and programmable edge to run logic close to users',
  'Digital media, e-commerce, and tech companies needing low-latency content delivery',
  'Launched new edge compute platform with serverless WebAssembly support',
  'Expand security and observability capabilities on edge platform',
  'Focused on developer control and programmability at the network edge'
),
(
  'Ethan Scott',
  'Teleport',
  'VP of Infrastructure Access',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Infrastructure access platform for zero trust security',
  'Identity-native access platform for engineers to access infrastructure without VPNs',
  'Eliminate privileged access risks while giving engineers seamless infrastructure access',
  'Enterprise engineering teams managing SSH, Kubernetes, and database access securely',
  'Launched new machine identity and workload access management features',
  'Expand zero trust access to cover all infrastructure types',
  'Focused on replacing legacy VPN and privileged access management solutions'
),
(
  'Maria Lopez',
  'Spacelift',
  'Head of Infrastructure Automation',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Collaborative infrastructure orchestration platform',
  'Policy-driven IaC orchestration platform for Terraform, Pulumi, and CloudFormation',
  'Enable platform engineering teams to manage IaC workflows with strong governance controls',
  'Platform engineering teams at companies with complex multi-team infrastructure operations',
  'Launched new drift detection and automated remediation for Terraform stacks',
  'Expand support for additional IaC tools and cloud providers',
  'Focused on bringing compliance and governance to infrastructure automation'
),
(
  'Jason Lee',
  'Cortex',
  'Director of Engineering Effectiveness',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Internal developer portal and service catalog platform',
  'Developer portal platform for service ownership, standards enforcement, and self-service',
  'Give engineering teams a clear view of service health and ownership to improve accountability',
  'Enterprise engineering organizations managing hundreds of internal services',
  'Launched new AI-powered service scorecard recommendations',
  'Expand from catalog into full internal developer platform capabilities',
  'Focused on improving engineering team productivity and service reliability'
),
(
  'Ashley Turner',
  'Doppler',
  'Head of Secrets Management',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Mid-Market'],
  'Secrets management and environment variable platform',
  'Universal secrets manager for syncing environment variables across apps and infrastructure',
  'Eliminate secrets sprawl and environment configuration errors across teams and deployments',
  'Engineering teams managing environment configuration across multiple services and environments',
  'Launched new secrets rotation automation for API keys and database credentials',
  'Expand into broader infrastructure security beyond secrets management',
  'Focused on developer experience and reducing configuration-related production incidents'
),
(
  'Brandon Harris',
  'Codefresh',
  'VP of GitOps Platform',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Enterprise GitOps platform for Kubernetes application delivery',
  'GitOps-based continuous delivery platform for Kubernetes applications',
  'Enable teams to manage application delivery through declarative Git workflows',
  'Enterprise Kubernetes adopters standardizing deployment workflows across teams',
  'Launched new progressive delivery visualization dashboard for canary releases',
  'Expand enterprise support and compliance features around GitOps workflows',
  'Focused on safe and observable application delivery through GitOps practices'
),
(
  'Tiffany Clark',
  'Wiz',
  'Director of Cloud Security',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Cloud security platform for risk detection and remediation',
  'Agentless cloud security platform for multi-cloud vulnerability and risk assessment',
  'Give security and DevOps teams a comprehensive view of cloud risks without deployment friction',
  'Enterprise companies with complex multi-cloud environments and security compliance requirements',
  'Launched new Wiz Code for security scanning earlier in the development cycle',
  'Expand from CSPM into full cloud-native application protection platform',
  'Focused on reducing the time from risk discovery to remediation'
),
(
  'Nicholas Brown',
  'Sysdig',
  'Head of Container Security',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Enterprise'],
  'Container and cloud security platform based on open source Falco',
  'Runtime security and cloud security posture management platform',
  'Detect and respond to threats in cloud-native environments in real time',
  'Enterprise security and DevOps teams running Kubernetes workloads in production',
  'Launched new AI-powered threat detection using generative AI for alert investigation',
  'Expand from container security into full cloud security platform',
  'Focused on real-time runtime threat detection alongside posture management'
),
(
  'Stephanie Martinez',
  'Temporal',
  'VP of Distributed Systems',
  'DevOps / Infrastructure',
  ARRAY['SaaS', 'B2B', 'Platform'],
  'Workflow orchestration platform for resilient distributed applications',
  'Open-source durable workflow execution platform for microservices',
  'Enable developers to build reliable distributed applications that can handle failures without complex retry logic',
  'Engineering teams building event-driven and microservice-based applications',
  'Launched new cloud-hosted Temporal service with enterprise SLAs',
  'Expand into enterprise market with compliance and governance features',
  'Focused on simplifying resilient application development for distributed systems teams'
);
